version: '3.7'

services:

  instrumentenplatform:
    container_name: instrumentenplatform
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'